sonar.projectKey=rpx-xui-manage-organisations
sonar.projectName=rpx-xui-manage-organisations
sonar.projectVersion=0.0.1
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=test/**,config/**,api/**/templates/**,src/public/**,src/environments/**,**/*.html,**/*.scss,src/app/app.constants.ts,src/app/utils/app-utils.ts,src/app/services/appInsightsWrapper.ts

sonar.javascript.lcov.reportPaths=reports/tests/coverage/ng/lcov-report/lcov.info
client.sonar.ts.tslint.configPath=tslint.json
client.sonar.ts.coverage.lcovReportPath=reports/tests/coverage/ng/lcov-report/lcov.info
