apiVersion: v2
name: xui-mo-webapp
home: https://github.com/hmcts/rpx-xui-manage-organisations
version: 1.1.19
description: Expert UI
maintainers:
  - name: HMCTS RPX XUI
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
  - name: ccd
    version: 9.2.2
    repository: 'oci://hmctspublic.azurecr.io/helm'
    tags:
      - ccd-idam-pr
  - name: xui-webapp
    version: ~1.0.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: xui-webapp.enabled
  - name: xui-mo-webapp
    version: ~1.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: xui-mo-webapp.enabled
  - name: aac-manage-case-assignment
    version: ~0.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: aac-manage-case-assignment.enabled
  - name: idam-pr
    version: 2.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: idam-pr.enabled
  - name: ccd-case-document-am-api
    version: 1.7.14
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd-case-document-am-api.enabled
#    Work Allocation
  - name: wa
    version: ~1.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.enabled
  - name: ccd-message-publisher
    version: ~0.1.7
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.enabled
  - name: servicebus
    version: ~1.2.1
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: servicebus.enabled
  - name: postgresql
    version: ~1.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: postgresql.enabled
  - name: am-org-role-mapping-service
    version: ~0.0.66
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: am-org-role-mapping-service.enabled