apiVersion: v2
name: xui-mo-webapp
home: https://github.com/hmcts/rpx-xui-manage-organisations
version: 1.1.3
description: Expert UI
maintainers:
  - name: HMCTS RPX XUI
dependencies:
  - name: nodejs
    version: 2.4.1
    repository: '@hmctspublic'
  - name: redis
    version: 15.7.6
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: idam-pr
    version: ~2.2.6
    repository: '@hmctspublic'
    condition: idam-pr.enabled

