apiVersion: v2
name: xui-mo-webapp
home: https://github.com/hmcts/rpx-xui-manage-organisations
version: 1.1.4
description: Expert UI
maintainers:
  - name: HMCTS RPX XUI
dependencies:
  - name: nodejs
    version: 1.0.210
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: redis
    version: 10.6.18
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: idam-pr
    version: ~2.2.6
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled

