export default {
    health: {
        ccdDataApi: 'http://ccd-data-store-api-aat.service.core-compute-aat.internal/health',
        ccdDefApi: 'http://ccd-definition-store-api-aat.service.core-compute-aat.internal/health',
        feeAndPayApi: 'http://payment-api-aat.service.core-compute-aat.internal/health',
        idamApi: 'https://idam-api.aat.platform.hmcts.net/health',
        idamWeb: 'https://idam-web-public.aat.platform.hmcts.net/health',
        rdProfessionalApi: 'http://rd-professional-api-aat.service.core-compute-aat.internal/health',
        s2s: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal/health',
    },
    jurisdictions: [
        { id: 'SSCS' },
        { id: 'AUTOTEST1' },
        { id: 'DIVORCE' },
        { id: 'PROBATE' },
        { id: 'PUBLICLAW' },
        { id: 'bulkscan' },
        { id: 'BULKSCAN' },
        { id: 'IA' },
        { id: 'EMPLOYMENT' },
        { id: 'CMC' },
    ],
    logging: 'debug',
    secureCookie: false,
    services: {
        ccdDataApi: 'http://ccd-data-store-api-aat.service.core-compute-aat.internal',
        ccdDefApi: 'http://ccd-definition-store-api-aat.service.core-compute-aat.internal',
        feeAndPayApi: 'http://payment-api-aat.service.core-compute-aat.internal',
        idamApi: 'https://idam-api.aat.platform.hmcts.net',
        idamWeb: 'https://idam-web-public.aat.platform.hmcts.net',
        rdProfessionalApi: 'http://rd-professional-api-aat.service.core-compute-aat.internal',
        s2s: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal',
    },
    sessionSecret: 'secretSauce',
    useProxy: false,
};
