export default {
    health: {
        ccdDataApi: 'http://ccd-data-store-api-prod.service.core-compute-prod.internal/health',
        ccdDefApi: 'http://ccd-definition-store-api-prod.service.core-compute-prod.internal/health',
        idamApi: 'https://idam-api.platform.hmcts.net/health',
        idamWeb: 'https://hmcts-access.service.gov.uk/health',
        rdProfessionalApi: 'http://rd-professional-api-prod.service.core-compute-prod.internal/health',
        s2s: 'http://rpe-service-auth-provider-prod.service.core-compute-prod.internal/health',
    },
    jurisdictions: [
        { id: 'SSCS' },
        { id: 'AUTOTEST1' },
        { id: 'DIVORCE' },
        { id: 'PROBATE' },
        { id: 'PUBLICLAW' },
        { id: 'bulkscan' },
        { id: 'BULKSCAN' },
        { id: 'IA' },
        { id: 'EMPLOYMENT' },
        { id: 'CMC' },
    ],
    logging: 'debug',
    secureCookie: true,
    services: {
        ccdDataApi: 'http://ccd-data-store-api-prod.service.core-compute-prod.internal',
        ccdDefApi: 'http://ccd-definition-store-api-prod.service.core-compute-prod.internal',
        idamApi: 'https://idam-api.platform.hmcts.net',
        idamWeb: 'https://hmcts-access.service.gov.uk',
        rdProfessionalApi: 'http://rd-professional-api-prod.service.core-compute-prod.internal',
        s2s: 'http://rpe-service-auth-provider-prod.service.core-compute-prod.internal',
    },
    sessionSecret: 'secretSauce',
    useProxy: false,
};
