import { LovRefDataModel } from '../../shared/models/lovRefData.model';

export const OTHER_ORGANISATION_TYPES_REF_DATA: LovRefDataModel[] = [
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'AccommodationAndFood',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Accommodation & food'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'AccountancyBankingAndFinance',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Accountancy, banking and finance'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'AdminAndSupport',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Admin and support'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'BusinessConsultingAndManagement',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Business, consulting and management'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'CharityAndVoluntaryWork',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Charity and voluntary work'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'CharteredSurveyors',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Chartered surveyors'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'Conveyancing',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Conveyancing'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'CreativeArtsAndDesign',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Creative arts and design'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'Education',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Education'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'EnergyAndUtilities',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Energy and utilities'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'EngineeringAndManufacturing',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Engineering and manufacturing'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'EnvironmentAndAgriculture',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Environment and agriculture'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'FinancialServices',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Financial services'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'Healthcare',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Healthcare'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'HospitalityAndEventsManagement',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Hospitality and events management'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'ITAndCommunications',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'IT & communications'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'LawEnforcementAndSecurity',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Law enforcement and security'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'LeisureSportAndTourism',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Leisure, sport and tourism'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'MarketingAdvertisingAndPR',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Marketing, advertising and PR'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'MediaAndInternet',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Media and internet'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'MiningAndQuarrying',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Mining and quarrying'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'NotForProfit',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Not for profit'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'PublicNotaries',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Public notaries'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'ProfessionalAndTechnical',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Professional & technical'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'PropertyAndConstruction',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Property and construction'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'PublicSectorAndDefence',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Public sector & defence'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'PublicServicesAndAdministration',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Public services and administration'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'RealEstateActivities',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Real estate activities'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'RecruitmentAndHR',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Recruitment and HR'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'RetailAndWholesale',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Retail & wholesale'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'Sales',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Sales'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'ScienceAndPharmaceuticals',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Science and pharmaceuticals'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'SocialCare',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Social care'
  },
  {
    active_flag: 'Y',
    category_key: 'OtherOrgType',
    child_nodes: null,
    hint_text_cy: '',
    hint_text_en: '',
    key: 'TransportAndLogistics',
    lov_order: null,
    parent_category: '',
    parent_key: '',
    value_cy: '',
    value_en: 'Transport and logistics'
  }
];
