ccd_data_api_service = "http://ccd-data-store-api-demo.service.core-compute-demo.internal"
ccd_definition_api_service = "http://ccd-definition-store-api-demo.service.core-compute-demo.internal"
idam_api_service = "https://idam-api.aat.platform.hmcts.net"
idam_web_service = "https://idam-web-public.aat.platform.hmcts.net"
rd_professional_api_service = "http://rd-professional-api-aat.service.core-compute-aat.internal"
s2s_service = "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
fee_and_pay_api = "http://payment-api-aat.service.core-compute-aat.internal"
